### ISSUE TITLE
Any way to not display the sidebar on the front page?

### ISSUE THREAD

**Issue by danyork** [ScottSmith95/Decode#29]
Scott,

MANY thanks for making this truly awesome theme!  A question for you - is there any way to NOT display the "always-on" sidebar on the front page of site with a statically-configured front page?

I have a site where I'd like to have the sidebar always visible on all the interior pages of the site - but I'd like to have the home page have the cleaner look of not having the sidebar.  I went through your many various options (which are excellent) but couldn't find any way to do this.

If there isn't a way to do this, then I'll toss this out as a potential feature request to consider.

Many thanks again for making this great theme and making it freely available.

Dan

**Comment by ScottSmith95** [comment]
Sorry for being super late on this, but if you are still curious, try changing line 55 on footer.php to: 
`<?php if ( get_theme_mod( 'show_sidebar', true ) == true && ! is_front_page() ) : ?>`
