### ISSUE TITLE
Hard coded http connections

### ISSUE THREAD

**Issue by cschildhorn** [ScottSmith95/Decode#33]
Tried to use Decode for https only. But the site includes other resources which are not secure e.g. the social icons (e.g. YouTube or Soundcloud) or some w3.org stuff use http for no obvious reason. Most external sources should be reachable in https too.

**Comment by ScottSmith95** [comment]
Do you have a link to this site? The social icons only have links to these possibly non-https sites, but the icons themselves are served from your site, which should be https—in fact, they are inline SVGs so they aren't even an external resource.

**Comment by cschildhorn** [comment]
Ok sorry. Perhaps the source could be a plugin I guess. But I thought I checked this before writing you. 

The site is https://www.chriscosy.de

**Comment by ScottSmith95** [comment]
You might want to check your site URL settings to see if they are https. I’m pretty sure this isn’t a Decode thing. :)
