### ISSUE TITLE
Large monospace fonts after 3.0.6

### ISSUE THREAD

**Issue by alanorth** [ScottSmith95/Decode#35]
I updated to 3.0.6 and now all code blocks are very large, including inline as well as `<pre><code>`. Could this be due to normalize?

![big-fonts](https://cloud.githubusercontent.com/assets/191754/6155384/e948a2ae-b243-11e4-983d-fdf4bc5bc2b4.png)

Post in question is: https://mjanja.ch/2014/12/maps-and-custom-error-pages-in-nginx/

**Comment by ScottSmith95** [comment]
This is definitely because of Normalize. Methinks the font should be quite a bit smaller, no? ;)

**Comment by alanorth** [comment]
Definitely should be smaller. :)

**Comment by ScottSmith95** [comment]
Just to clarify, is there also an issue with the HTML output? Is `<pre><code>` the same wrapping as previously seen?

**Comment by alanorth** [comment]
The code blocks are now back to normal. :clap:

**Comment by ScottSmith95** [comment]
Sweet! This will get merged in with the next release. Thanks for opening up a ticket!
