### ISSUE TITLE
Youtube Icon

### ISSUE THREAD

**Issue by Mantrin185** [ScottSmith95/Decode#37]
Hi Scott,

Could you add support for YouTube's new URL system? 
Or maybe an easier way would be to unlock it from YouTube.com/user/[your_id]?

Perhaps just make it YouTube.com/[custom_text] so that we could enter whatever url Youtube decides to change it to. So far they have /user/, /channel/, and now /c/.

Thank you for your time and I love your theme,
- Jason

**Comment by Mantrin185** [comment]
Perfect fix, Scott. Thank you!

**Comment by ScottSmith95** [comment]
Oh yes, I forgot to close this issue. I'm happy this solution works for you!
