### ISSUE TITLE
Is there any plan to port Decode to pelican

### ISSUE THREAD

**Issue by leaveye** [ScottSmith95/Decode#40]
I like Decode theme very much. For the last years, I have written a few "notes" on my server in Wordpress. I do not understand JS, CCS, and HTML. Since I decided to build a blog on pelican, I have just tried to do porting for a few hours, and gived up. So if you could, or any one would, I will be very happy to use it in my new blog again.

**Comment by ScottSmith95** [comment]
Not at this time since I've not heard much about it or had many requests. I ported Decode to Ghost because I started using GHost and backed it on Kickstarter in its early days.
