### ISSUE TITLE
Dropdown in menu bar not working in Google Chrome 43.0.2357.130

### ISSUE THREAD

**Issue by ET-Bent** [ScottSmith95/Decode#42]
After the last update the drop down menus don't work anymore in Google Chrome. In the latest Firefox and Chromium everything works fine. This issue is present on the Linux and Windows Version of Google Chrome (not tested on Mac).

Decode version:  3.0.8
Google Chrome version: 43.0.2357.130 (64-bit)

Let me know if you need additional information.

**Comment by ScottSmith95** [comment]
This is due to Modernizr breaking, I've got a fix ready for submission.

**Comment by ET-Bent** [comment]
Thats awesome, thanks!

**Comment by ET-Bent** [comment]
Okay interesting Firefox also started having issues now.

**Comment by baalansellers** [comment]
So do I need to manually edit the javascript to fix the issue, or will this be released as an update through Wordpress sometime soon?

**Comment by ScottSmith95** [comment]
That’s an option, but hopefully the update will be approved soon. It’s like the App Store—out of my hands right now.

**Comment by baalansellers** [comment]
Gatcha, no worries.

**Comment by ET-Bent** [comment]
Cool thanks nervously waiting here! 

I would like to use this to thank you for your theme, really good looking, I'm glad I found it long ago :D 

So THANKS!

**Comment by ScottSmith95** [comment]
I'm waiting as nervously as you are, although I'm confident the update will be approved. In the future, WordPress.org will start auto-approving theme updates so fixes like this won't have a wait time.

**Comment by ET-Bent** [comment]
Nice that will be awesome. Well I didn't know before that themes had to be approved though...

**Comment by ScottSmith95** [comment]
The WordPress Theme Review team approved an update with the fix this morning. The update is available now! Thanks for hanging in there.
