### ISSUE TITLE
Request: hide 'Share this:'

### ISSUE THREAD

**Issue by maique** [ScottSmith95/Decode#49]
Is there a way to get rid of the social sharing buttons on every post ? Tried to find a setting for this but was unable to do so.

Thanks.

**Comment by maique** [comment]
Never mind, figured it how. Sorry about that, new user.

**Comment by ScottSmith95** [comment]
Thanks for clearing this out. Let me know if there is anything I can help with in the future.

**Comment by maique** [comment]
Thanks. Just installed WordPress after a few years away from it, and your theme is perfect for what I needed, love it. Great work, thanks for sharing.
